Move to node:current-alpine docker builder
to ensure node works with the openssl version:
` > [builder 5/5] RUN echo "VITE_API_HOSTNAME=/" > .env.local &&     npm i &&     npm run build:
0.055 Error relocating /usr/bin/node: EVP_MD_CTX_get_size_ex: symbol not found
------
Dockerfile:9
--------------------
   8 |
   9 | >>> RUN echo "VITE_API_HOSTNAME=${VITE_API_HOSTNAME}" > .env.local && \
  10 | >>>     npm i && \
  11 | >>>     npm run build
  12 |
--------------------
ERROR: failed to solve: process "/bin/sh -c echo \"VITE_API_HOSTNAME=${VITE_API_HOSTNAME}\" > .env.local &&     npm i &&     npm run build" did not complete successfully: exit code: 127`